server:
  port: 9999

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.238:3306/test?serverTimezone=GMT
    username: root
    password: admin

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*